/**
 * Comprehensive Korean text restoration - Phase 2
 * Fixes ALL remaining corrupted Korean characters across all files
 */
const fs = require('fs');
const path = require('path');
const BASE = 'c:/Users/KYUNG005/Desktop/spacematch/src';

// [file, corrupted, correct] - each pair is a unique substring replacement
const fixes = [
    // ============================================================
    // SuperAdminDatabase.jsx (1 line)
    // ============================================================
    ['pages/admin/SuperAdminDatabase.jsx',
        "showToast('?�️ DEV 모드?�서???�이???�정??불�??�합?�다.\\nPROD 모드�??�환?�주?�요.'",
        "showToast('⚙️ DEV 모드에서는 데이터 수정이 불가능합니다.\\nPROD 모드로 전환해주세요.'"],

    // ============================================================
    // AuthContext.jsx (4 lines)
    // ============================================================
    ['context/AuthContext.jsx',
        "\"?�버 ?�류' 발생?�습?�다.\"",
        "\"서버 오류가 발생했습니다.\""],
    ['context/AuthContext.jsx',
        "\"?�원�???처리 �??�류\"",
        "\"회원가입 처리 중 오류\""],
    ['context/AuthContext.jsx',
        "'?�로???�정???�패?�습?�다.'",
        "'프로필 수정에 실패했습니다.'"],
    ['context/AuthContext.jsx',
        "\"?�버 ?�류' 발생?�습?�다. ?�시 ?�도?�주?�요.\"",
        "\"서버 오류가 발생했습니다. 다시 시도해주세요.\""],

    // ============================================================
    // NotificationPrompt.jsx (10 lines)
    // ============================================================
    ['components/NotificationPrompt.jsx',
        "?�림??켜보?�요! ?��",
        "알림을 켜보세요! 🔔"],
    ['components/NotificationPrompt.jsx',
        "?�로???�식???�치 마세",
        "새로운 소식을 놓치지 마세요"],
    ['components/NotificationPrompt.jsx',
        "?�점 ?�청 결과 ?�림",
        "입점 신청 결과 알림"],
    ['components/NotificationPrompt.jsx',
        "?�인/반려 결과�?바로 ?�인?�세",
        "승인/반려 결과를 바로 확인하세요"],
    ['components/NotificationPrompt.jsx',
        "커�??�티 ?�동 ?�림",
        "커뮤니티 활동 알림"],
    ['components/NotificationPrompt.jsx',
        "?��?, ???��????�치�? 마세",
        "댓글, 좋아요를 놓치지 마세요"],
    ['components/NotificationPrompt.jsx',
        "?�로??공간 ?�보",
        "새로운 공간 정보"],
    ['components/NotificationPrompt.jsx',
        "??공간 ?�록 �??�태 �?�??�림",
        "새 공간 등록 및 상태 변경 알림"],
    ['components/NotificationPrompt.jsx',
        "?�림 받기",
        "알림 받기"],
    ['components/NotificationPrompt.jsx',
        "?�중???�기",
        "나중에 하기"],

    // ============================================================
    // AdminDashboard.jsx (22 lines)
    // ============================================================
    ['pages/admin/AdminDashboard.jsx',
        "title: isApprove ? '공간 ?�인' : '공간 반려'",
        "title: isApprove ? '공간 승인' : '공간 반려'"],
    ['pages/admin/AdminDashboard.jsx',
        "? '??공간???�인?�시겠습?�까?' : '??공간??반려?�시겠습?�까?'",
        "? '이 공간을 승인하시겠습니까?' : '이 공간을 반려하시겠습니까?'"],
    ['pages/admin/AdminDashboard.jsx',
        "confirmLabel: isApprove ? '?�인' : '반려'",
        "confirmLabel: isApprove ? '승인' : '반려'"],
    ['pages/admin/AdminDashboard.jsx',
        ">?�영<",
        ">운영중<"],
    ['pages/admin/AdminDashboard.jsx',
        ">?�사<",
        ">심사중<"],
    ['pages/admin/AdminDashboard.jsx',
        "?�체 공간 ?�황",
        "전체 공간 현황"],
    ['pages/admin/AdminDashboard.jsx',
        "?�체 공간</span>",
        "전체 공간</span>"],
    ['pages/admin/AdminDashboard.jsx',
        ">?�인 ??<",
        ">승인 대기<"],
    ['pages/admin/AdminDashboard.jsx',
        ">반려?<",
        ">반려됨<"],
    ['pages/admin/AdminDashboard.jsx',
        "'?�인 ?�료', '반려 ?�료'",
        "'승인 완료', '반려 완료'"],
    ['pages/admin/AdminDashboard.jsx',
        "?�점 ?�청 ?�황",
        "입점 신청 현황"],
    ['pages/admin/AdminDashboard.jsx',
        "?�류 ?',",
        "오류 발생',"],
    ['pages/admin/AdminDashboard.jsx',
        "?�점 ?�청 관리",
        "입점 신청 관리"],
    ['pages/admin/AdminDashboard.jsx',
        "?�직 ?�록???�습?�다",
        "아직 등록된 공간이 없습니다"],
    ['pages/admin/AdminDashboard.jsx',
        "?�록??공간???�습?�다",
        "등록된 공간이 없습니다"],

    // ============================================================
    // AdminCancellations.jsx (22 lines)
    // ============================================================
    ['pages/admin/AdminCancellations.jsx',
        "'취소 ?�청 로드 ?�패:'",
        "'취소 신청 로드 실패:'"],
    ['pages/admin/AdminCancellations.jsx',
        "const actionLabel = action === 'approved' ? '?�인' : '거절'",
        "const actionLabel = action === 'approved' ? '승인' : '거절'"],
    ['pages/admin/AdminCancellations.jsx',
        "title: `취소 ?�청 ${actionLabel}`",
        "title: `취소 신청 ${actionLabel}`"],
    ['pages/admin/AdminCancellations.jsx',
        "message: `??취소 ?�청??${actionLabel}?�시겠습?�까?`",
        "message: `이 취소 신청을 ${actionLabel}하시겠습니까?`"],
    ['pages/admin/AdminCancellations.jsx',
        "confirmLabel: actionLabel + '?�기'",
        "confirmLabel: actionLabel + '하기'"],
    ['pages/admin/AdminCancellations.jsx',
        "'처리 ?�료'",
        "'처리 완료'"],
    ['pages/admin/AdminCancellations.jsx',
        "'처리 ?�패'",
        "'처리 실패'"],
    ['pages/admin/AdminCancellations.jsx',
        "'처리 ??오류 발생'",
        "'처리 중 오류 발생'"],
    ['pages/admin/AdminCancellations.jsx',
        "취소 ?�청 관리",
        "취소 신청 관리"],
    ['pages/admin/AdminCancellations.jsx',
        ">?? {requests.filter",
        ">총 {requests.filter"],
    ['pages/admin/AdminCancellations.jsx',
        "건의 취소 ?�청",
        "건의 취소 신청"],
    ['pages/admin/AdminCancellations.jsx',
        ">?�체<",
        ">전체<"],
    ['pages/admin/AdminCancellations.jsx',
        ">??�?<",
        ">대기<"],
    ['pages/admin/AdminCancellations.jsx',
        ">?�인<",
        ">승인<"],
    ['pages/admin/AdminCancellations.jsx',
        "?�청??없습?�다",
        "신청이 없습니다"],
    ['pages/admin/AdminCancellations.jsx',
        "?? ?�청?",
        "취소 신청자"],
    ['pages/admin/AdminCancellations.jsx',
        "?? 공간",
        "관련 공간"],
    ['pages/admin/AdminCancellations.jsx',
        "취소 ?�유",
        "취소 사유"],
    ['pages/admin/AdminCancellations.jsx',
        "?�보?? ?�함",
        "정보가 포함"],

    // ============================================================
    // VendorDashboard.jsx (29 lines)
    // ============================================================
    ['pages/vendor/VendorDashboard.jsx',
        "?�녕?�세?? {user.name}?? ?��",
        "안녕하세요, {user.name}님 👋"],
    ['pages/vendor/VendorDashboard.jsx',
        "공간 비즈?�스???�체 ?�황???�눈???�인?�세??",
        "공간 비즈니스의 전체 현황을 한눈에 확인하세요"],
    ['pages/vendor/VendorDashboard.jsx',
        ">?�체 공간<",
        ">전체 공간<"],
    ['pages/vendor/VendorDashboard.jsx',
        ">?�영 {activeVenues}<",
        ">운영 {activeVenues}<"],
    ['pages/vendor/VendorDashboard.jsx',
        ">?�사 {pendingVenues}<",
        ">심사 {pendingVenues}<"],
    ['pages/vendor/VendorDashboard.jsx',
        ">??�??�청<",
        ">입점신청<"],
    ['pages/vendor/VendorDashboard.jsx',
        "바로�?�?<ChevronRight",
        "바로가기 <ChevronRight"],
    ['pages/vendor/VendorDashboard.jsx',
        ">?�점 ??<",
        ">입점 현황<"],
    ['pages/vendor/VendorDashboard.jsx',
        ">�?{totalApps}�??�청<",
        ">총 {totalApps}건 신청<"],
    ['pages/vendor/VendorDashboard.jsx',
        ">?�인<",
        ">승인<"],
    ['pages/vendor/VendorDashboard.jsx',
        "공간�??�황",
        "공간별 현황"],
    ['pages/vendor/VendorDashboard.jsx',
        "공간 �?�?<ChevronRight",
        "공간 관리 <ChevronRight"],
    ['pages/vendor/VendorDashboard.jsx',
        "?�직 ?�록??공간???�습?�다.",
        "아직 등록된 공간이 없습니다."],
    ['pages/vendor/VendorDashboard.jsx',
        "�?공간 ?�록?�기 '",
        "새 공간 등록하기 →"],
    ['pages/vendor/VendorDashboard.jsx',
        "vs.status === 'approved' ? '?�영'",
        "vs.status === 'approved' ? '운영중'"],
    ['pages/vendor/VendorDashboard.jsx',
        "vs.status === 'pending' ? '?�사'",
        "vs.status === 'pending' ? '심사중'"],
    ['pages/vendor/VendorDashboard.jsx',
        ">?�점 {vs.approved}�?· ?�청 {vs.total}<",
        ">입점 {vs.approved}명 · 신청 {vs.total}<"],
    ['pages/vendor/VendorDashboard.jsx',
        "최근 ?�청",
        "최근 신청"],
    ['pages/vendor/VendorDashboard.jsx',
        "?�체보기 <ChevronRight",
        "전체보기 <ChevronRight"],
    ['pages/vendor/VendorDashboard.jsx',
        "?�직 ?�청???�습?�다.",
        "아직 신청이 없습니다."],
    ['pages/vendor/VendorDashboard.jsx',
        "timeLabel = `${diffHr}?�간 ??`",
        "timeLabel = `${diffHr}시간 전`"],
    ['pages/vendor/VendorDashboard.jsx',
        "timeLabel = `${diffMin}�???`",
        "timeLabel = `${diffMin}분 전`"],
    ['pages/vendor/VendorDashboard.jsx',
        "{app.applicant_name || '?�청'}",
        "{app.applicant_name || '신청자'}"],
    ['pages/vendor/VendorDashboard.jsx',
        "???�점 ?�청",
        "에 입점 신청"],
    ['pages/vendor/VendorDashboard.jsx',
        "?�청 ?�황 ?�약",
        "신청 현황 요약"],
    ['pages/vendor/VendorDashboard.jsx',
        ">??�?<",
        ">대기<"],
    ['pages/vendor/VendorDashboard.jsx',
        ">?�체 ?�인<",
        ">전체 확인<"],
    ['pages/vendor/VendorDashboard.jsx',
        "?�인 {approvedApps} · ??�?{pendingApps} · 거절 {rejectedApps}",
        "승인 {approvedApps} · 대기 {pendingApps} · 거절 {rejectedApps}"],
    ['pages/vendor/VendorDashboard.jsx',
        ">�?{totalApps}<",
        ">총 {totalApps}<"],

    // ============================================================
    // VendorSellerDirectory.jsx (remaining lines after category fixes)
    // ============================================================
    ['pages/vendor/VendorSellerDirectory.jsx',
        "'????목록 로드 ?�패:'",
        "'셀러 목록 로드 실패:'"],
    ['pages/vendor/VendorSellerDirectory.jsx',
        "?????�색",
        "셀러 검색"],
    ['pages/vendor/VendorSellerDirectory.jsx',
        "?�점 ?�망 ????브랜??�?찾아보세",
        "입점 희망 셀러 브랜드를 찾아보세요"],
    ['pages/vendor/VendorSellerDirectory.jsx',
        "placeholder=\"브랜?�명, 카테고리, ?�스??그램?�로 �???..",
        "placeholder=\"브랜드명, 카테고리, 인스타그램으로 검색.."],
    ['pages/vendor/VendorSellerDirectory.jsx',
        "?�터 & ?�렬",
        "필터 & 정렬"],
    ['pages/vendor/VendorSellerDirectory.jsx',
        ">?�목 (카테고리)<",
        ">업종 (카테고리)<"],
    ['pages/vendor/VendorSellerDirectory.jsx',
        ">?�체 ?�목<",
        ">전체 업종<"],
    ['pages/vendor/VendorSellerDirectory.jsx',
        ">?�렬<",
        ">정렬<"],
    ['pages/vendor/VendorSellerDirectory.jsx',
        ">최신 �??�순<",
        ">최신 가입순<"],
    ['pages/vendor/VendorSellerDirectory.jsx',
        ">?�래??�??�순<",
        ">오래된 가입순<"],
    ['pages/vendor/VendorSellerDirectory.jsx',
        ">?�름??(�??�하)<",
        ">이름순 (가→하)<"],
    ['pages/vendor/VendorSellerDirectory.jsx',
        ">?�름??(?�→ㅎ)<",
        ">이름순 (하→ㄱ)<"],
    ['pages/vendor/VendorSellerDirectory.jsx',
        ">?�청 ??많�?<",
        ">신청 많은순<"],
    ['pages/vendor/VendorSellerDirectory.jsx',
        "?�터 초기??",
        "필터 초기화"],
    ['pages/vendor/VendorSellerDirectory.jsx',
        ">?�위 ?�출<",
        ">상위 노출<"],
    ['pages/vendor/VendorSellerDirectory.jsx',
        "명의 ' ",
        "명의 셀러 "],
    ['pages/vendor/VendorSellerDirectory.jsx',
        "�???결과�? ?�습?�다",
        "검색 결과가 없습니다"],
    ['pages/vendor/VendorSellerDirectory.jsx',
        "?�터 조건??�?경해 보세",
        "필터 조건을 변경해 보세요"],
    ['pages/vendor/VendorSellerDirectory.jsx',
        "?�점 ?�청 <span",
        "입점 신청 <span"],
    ['pages/vendor/VendorSellerDirectory.jsx',
        ">{seller.app_count}</span>�?",
        ">{seller.app_count}</span>건"],
    ['pages/vendor/VendorSellerDirectory.jsx',
        "�??�일: {new Date",
        "가입일: {new Date"],
    ['pages/vendor/VendorSellerDirectory.jsx',
        ">?�매 ?�보<",
        ">판매 정보<"],
    ['pages/vendor/VendorSellerDirectory.jsx',
        "브랜???�개�? ?�록?��? ?�았?�니??",
        "브랜드 소개가 등록되지 않았습니다"],
    ['pages/vendor/VendorSellerDirectory.jsx',
        "?�품 ?�진",
        "제품 사진"],
    ['pages/vendor/VendorSellerDirectory.jsx',
        "alt={`?�품 ${idx + 1}`}",
        "alt={`제품 ${idx + 1}`}"],
    ['pages/vendor/VendorSellerDirectory.jsx',
        ">?�점 ?�청<",
        ">입점 신청<"],
    ['pages/vendor/VendorSellerDirectory.jsx',
        ">?�락�??�보<",
        ">연락처 정보<"],
    ['pages/vendor/VendorSellerDirectory.jsx',
        ">?�메<",
        ">이메일<"],
    ['pages/vendor/VendorSellerDirectory.jsx',
        ">?�락<",
        ">연락처<"],
    ['pages/vendor/VendorSellerDirectory.jsx',
        ">?�스??그램<",
        ">인스타그램<"],
    ['pages/vendor/VendorSellerDirectory.jsx',
        ">비즈?�스 ?�보<",
        ">비즈니스 정보<"],
    ['pages/vendor/VendorSellerDirectory.jsx',
        ">?�업?�등록번<",
        ">사업자등록번호<"],
    ['pages/vendor/VendorSellerDirectory.jsx',
        ">�??�일<",
        ">가입일<"],
];

// Process fixes
let totalFixed = 0;
const fileGroups = {};
for (const [relFile, corrupt, correct] of fixes) {
    const fullPath = path.join(BASE, relFile);
    if (!fileGroups[fullPath]) fileGroups[fullPath] = [];
    fileGroups[fullPath].push({ corrupt, correct });
}

for (const [filePath, replacements] of Object.entries(fileGroups)) {
    let content = fs.readFileSync(filePath, 'utf8');
    let fileFixed = 0;
    for (const { corrupt, correct } of replacements) {
        if (content.includes(corrupt)) {
            content = content.replace(corrupt, correct);
            fileFixed++;
        } else {
            console.log(`  ⚠ NOT FOUND in ${path.basename(filePath)}: "${corrupt.substring(0, 40)}..."`);
        }
    }
    if (fileFixed > 0) {
        fs.writeFileSync(filePath, content, 'utf8');
        console.log(`✅ ${path.relative(BASE, filePath)}: ${fileFixed} fixes`);
        totalFixed += fileFixed;
    }
}
console.log(`\nPhase 2 total: ${totalFixed} fixes applied`);
